# Read the Docs configuration file for lbxd
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the OS, set of tools, and commands to run
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.70"
  jobs:
    pre_build:
      # Install Rust dependencies and generate docs
      - cargo doc --no-deps --document-private-items
    post_build:
      # Copy Rust docs to build directory
      - mkdir -p $READTHEDOCS_OUTPUT/html/api
      - cp -r target/doc/* $READTHEDOCS_OUTPUT/html/api/ || true

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

# Optional but recommended, declare the formats you want to build
formats:
  - pdf
  - epub
